version : '3'
services:
  api:
    build: application/
    ports: 
      - "8080:80"
  db:
    build: db/
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: